UserSearch/Models/ErrorViewModel.cs
namespace UserSearch.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UserSearch/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UserSearch.Models;

namespace UserSearch.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UserSearch/Controllers/UserSearchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;
using UserSearch.Helpers;

namespace UserSearch.Controllers
{
    public class UserSearchController : Controller
    {
        private IConfiguration _configuration;

        public UserSearchController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        private string? GetConnectionString()
        {
            return _configuration.GetConnectionString("DefaultConnection");
        }

        #region User Search Param Entry Screen

        public IActionResult UserSearchParamEntryScreen()
        {
            ViewBag.UserNameList = ConversionHelper.BindDropDown(SqlHelper.GetUserNameList(GetConnectionString()));
            ViewBag.UserFieldList = ConversionHelper.BindDropDown(SqlHelper.GetUserFieldList(GetConnectionString()));
            
            return View();
        }

        [HttpPost]
        public object? GetSearchParamsByUserId(int UserId)
        {
            return SqlHelper.GetSearchParamsByUserId(GetConnectionString(), UserId);            
        }

        [HttpPost]
        public ActionResult SaveUserSearchParamEntry(int UserId, string SearchCriteria) 
        {
            SqlHelper.UpsertSearchPrams(GetConnectionString(), UserId, SearchCriteria);
            TempData["success"] = "User Search Parameter Saved Successfully...!";
            return RedirectToAction("UserSearchParamEntryScreen");
        }

        #endregion

        #region User Search Screen

        public IActionResult UserSearchScreen()
        {
            ViewBag.UserNameList = ConversionHelper.BindDropDown(SqlHelper.GetUserNameList(GetConnectionString()));
            ViewBag.RoleList = ConversionHelper.BindDropDown(SqlHelper.GetRoleList(GetConnectionString()));
            ViewBag.DepartmentList = ConversionHelper.BindDropDown(SqlHelper.GetDepartmentList(GetConnectionString()));           

            return View();
        }

        [HttpPost]
        public string SearchUserBySearchParams(int? userid = null, string? username=null, 
            string? role=null, DateTime? lastlogin=null, string? fname=null, string? lname=null, 
            string? department=null, DateTime? doj=null, int? mgrid = null, float? seniority=null, string? empcode = null)
        {
            return SqlHelper.SearchUserBySearchParams(GetConnectionString(), userid, username, role, lastlogin, fname,
                lname, department, doj, mgrid, seniority, empcode);
        }

        #endregion        

    }
}

UserSearch/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UserSearch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserSearch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserSearch.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha512-oe8OpYjBaDWPt2VmSFR+qYOdnTjeV9QPLJUeqZyprDEQvQLJ9C5PCFclxwNuvb/GQgQngdCXzKSFltuHD3eCxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                User Management
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="UserSearch" asp-action="UserSearchParamEntryScreen">Search Parameters Entry Screen</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="UserSearch" asp-action="UserSearchScreen">User Search Screen</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications"></partial>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UserSearch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UserSearch/Views/Shared/_Notifications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}

@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

UserSearch/Views/UserSearch/UserSearchParamEntryScreen.cshtml
@{
    ViewData["Title"] = "Search Parameters Entry Screen";
}

<div class="card">

    <div class="card-header">
        <div class="card-title">
            <h2>Search Parameters Entry Screen</h2>
            <br />
            <p style="color:red;font-style: italic;">
                * Please pay attention incase of input controls highlighted with red color,
                <br>this means that it requires valid input values to be supplied.
                <br><br> * Save Search Parameter button will be enabled only atleast 3 parameters are set.
            </p>
        </div>
    </div>

    <div class="card-body">

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.DropDownList("UserNameList", (IEnumerable<SelectListItem>)ViewBag.UserNameList, "--- Select User ---", new { @class = "form-control"})
                    <input type="hidden" id="UserId" />
                    <input type="hidden" id="Username" />
                    <br />
                </div>
            </div>
        </div>

        <div class="row" id="ParamEntryDiv" style="visibility:hidden">
            <div class="col-lg-12">
                <div class="form-group">
                    <table class="table table-bordered table-striped" id='tblParamsEntry'>
                        <thead class="bg-dark text-white">
                            <tr>
                                <td>Field Name</td>
                                <td>Data Type</td>
                                <td>Control Type</td>
                                <td>Contraint</td>
                                <td>Action</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    @Html.DropDownList("UserFieldList", (IEnumerable<SelectListItem>)ViewBag.UserFieldList, "--- Select ---", new { @class = "form-control"})
                                </td>
                                <td>
                                    @Html.DropDownList("DataType",Html.GetEnumSelectList(typeof(UserSearch.Data.DataType)) , "--- Select ---", new { @class = "form-control" })
                                </td>
                                <td>
                                    @Html.DropDownList("ControlType",Html.GetEnumSelectList(typeof(UserSearch.Data.ControlType)) , "--- Select ---", new { @class = "form-control" })
                                </td>
                                <td>
                                    @Html.DropDownList("Constraint",Html.GetEnumSelectList(typeof(UserSearch.Data.Constraint)) , "--- Select ---", new { @class = "form-control" })
                                </td>
                                <td width="20px"><input type="button" class="btn btn-primary" id="btnParamAdd" value="Add"></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="row" id="ParamDisplayDiv" style="visibility:hidden">
            <div class="col-lg-12">
                <div class="form-group">
                    <table class="table table-bordered table-striped" id='tblParams'>
                        <thead class="bg-dark text-white">
                            <tr>
                                <td>Field Name</td>
                                <td>Data Type</td>
                                <td>Control Type</td>
                                <td>Constraint</td>
                                <td width="20px">Action</td>
                            </tr>
                        </thead>
                        <tbody id="tblParamstblBody">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    
    <div id="FooterDiv" class="card-footer" style="visibility:hidden">
        <div class="col-lg-6">
            <div class="form-group">
                <input type="button" class="btn btn-success" id="btnParamSave" value="Save Search Parameter">
            </div>
        </div>
    </div>

</div>

<script src="~/js/UserSearchParamEntry.js" asp-append-version="true"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script type="text/javascript">

    var UserSearchParam = [];
    var SearchParamCount = 0;

    // User List dropdown selection change event handler.
    $('#UserNameList').change(function () {

        var row = '';
        UserSearchParam = [];

        // Clear the error color, incase it was previousely set.
        $('#UserFieldList').removeClass("error");
        $('#DataType').removeClass("error");
        $('#ControlType').removeClass("error");
        $('#Constraint').removeClass("error");

        // Set the hidden fields with the selected user dropdown values.
        $('#UserId').val($(this).val());
        $('#Username').val($('option:selected', $(this)).text());

        // Show and hide the divs.
        if ($('#UserId').val()) {
            $("#ParamEntryDiv").css("visibility", "visible");
            $("#ParamDisplayDiv").css("visibility", "visible");
            $("#FooterDiv").css("visibility", "visible");
        }
        else {
            $("#ParamEntryDiv").css("visibility", "hidden");
            $("#ParamDisplayDiv").css("visibility", "hidden");
            $("#FooterDiv").css("visibility", "hidden");
        }

        $.ajax({
            type: "POST",
            url: "/UserSearch/GetSearchParamsByUserId",
            data: { "UserId": $('#UserId').val() },
            success: function (response) {

                if (response) {

                    UserSearchParam = JSON.parse(response);
                    SearchParamCount = UserSearchParam.length;

                    if (SearchParamCount == 0) {
                        ShowEmptyParamRow();
                    }
                    else {
                        BuildUserSearchParamTable();
                    }
                }
                else {
                    SearchParamCount = UserSearchParam.length;
                    ShowEmptyParamRow();
                }
            },
            failure: function (response) { toastr.error(response.responseText) },
            error: function (response) { toastr.error(response.responseText) },
        });

    });

    // Add param button click event.
    $('#btnParamAdd').click(function () {

        var flgValid = true;
        var FieldName = '';
        var FieldName = '';
        var DataType = '';
        var ControlType = '';

        if (!$('#UserFieldList').val()) {
            flgValid = false;
            $('#UserFieldList').addClass("error");
        }
        else {
            $('#UserFieldList').removeClass("error");
            FieldName = $('option:selected', $('#UserFieldList')).text();
        }

        if (!$('#DataType').val()) {
            flgValid = false;
            $('#DataType').addClass("error");
        }
        else {
            $('#DataType').removeClass("error");
            DataType = $('option:selected', $('#DataType')).text();
        }

        if (!$('#ControlType').val()) {
            flgValid = false;
            $('#ControlType').addClass("error");
        }
        else {
            $('#ControlType').removeClass("error");
            ControlType = $('option:selected', $('#ControlType')).text();
        }

        if (!$('#Constraint').val()) {
            flgValid = false;
            $('#Constraint').addClass("error");
        }
        else {
            $('#Constraint').removeClass("error");
            Constraint = $('option:selected', $('#Constraint')).text();
        }

        if (flgValid) {

            if (!CheckIfSearchFieldPresent(FieldName)) {
                $('#UserFieldList').removeClass("error");
                UserSearchParam.push({ "FieldName": FieldName, "DataType": DataType, "ControlType": ControlType, "Constraint": Constraint });
                SearchParamCount = UserSearchParam.length;
                document.getElementById("btnParamSave").disabled = (SearchParamCount < 3);
                BuildUserSearchParamTable();
            }
            else {
                $('#UserFieldList').addClass("error");
            }

        }

    });

    // Save search parameters to the database.
    $('#btnParamSave').click(function () {

        $.ajax({
            type: "POST",
            url: "/UserSearch/SaveUserSearchParamEntry",
            data: { "UserId": $('#UserId').val(), "SearchCriteria": JSON.stringify(UserSearchParam) },
            success: function (response) {
                toastr.success('Search Parameter saved successfully...!')
                document.getElementById("btnParamSave").disabled = (SearchParamCount < 3);
            },
            failure: function (response) { toastr.error(response.responseText) },
            error: function (response) { toastr.error(response.responseText) },
        });

    });


</script>

UserSearch/Views/UserSearch/UserSearchScreen.cshtml
@{
    ViewData["Title"] = "User Search Screen";
}

<div class="card">

    <div class="card-header">
        <div class="card-title">
            <h2>User Search Screen</h2>
            <br />
            <p style="color:red;font-style: italic;">
                * Please pay attention incase of input controls highlighted with red color,
                <br>this means that it requires valid input values to be supplied.
                <br><br>* Search works on the contains basis for string field, not on the exact match.
            </p>
        </div>
    </div>

    <div class="card-body">

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.DropDownList("UserNameList", (IEnumerable<SelectListItem>)ViewBag.UserNameList, "--- Select User ---", new { @class = "form-control"})
                    <input type="hidden" id="UserId" />
                    <input type="hidden" id="Username" />
                    <br />
                </div>
            </div>
        </div>

        <div class="row" id="ParamSearchDiv" style="visibility:hidden">
            <div class="col-lg-12">
                <div class="form-group">
                    <table class="table table-bordered table-striped" id='tblParams'>
                        <thead class="bg-dark text-white">
                            <tr>
                                <td>Field Name</td>
                                <td>Field Value</td>
                            </tr>
                        </thead>
                        <tbody id="tblParamSearchBody">
                        </tbody>
                    </table>
                    <input type="button" class="btn btn-success" id="btnSearch" value="Search">
                </div>
            </div>
        </div>
        <br />
        <div class="row" id="UserDisplayDiv" style="visibility:hidden">
            <div class="col-lg-12">
                <div class="form-group">
                    <table class="table table-bordered table-striped" id='tblParams'>
                        <thead class="bg-dark text-white">
                            <tr>
                                <td>User Id</td>
                                <td>User Name</td>
                                <td>Role</td>
                                <td>Last Login</td>
                                <td>First Name</td>
                                <td>Last Name</td>
                                <td>Department</td>
                                <td>DOJ</td>
                                <td>Manager Id</td>
                                <td>Seniority</td>
                                <td>Employee Code</td>
                            </tr>
                        </thead>
                        <tbody id="tblUserDisplayBody">
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

</div>

<script src="~/js/UserSearch.js" asp-append-version="true"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script type="text/javascript">

    var UserSearchParam = [];
    var UserSearchResult = [];

    var SearchParamCount = 0;
    var UserSearchResultCount = 0;

    var UserNameList = @Html.Raw(Json.Serialize(ViewBag.UserNameList));
    var RoleList = @Html.Raw(Json.Serialize(ViewBag.RoleList));
    var DepartmentList = @Html.Raw(Json.Serialize(ViewBag.DepartmentList));

    // User List dropdown selection change event handler.
    $('#UserNameList').change(function () {

        var row = '';
        UserSearchParam = [];

        document.getElementById('tblParamSearchBody').innerHTML = '';

        // Set the hidden fields with the selected user dropdown values.
        $('#UserId').val($(this).val());
        $('#Username').val($('option:selected', $(this)).text());

        $("#ParamSearchDiv").css("visibility", "hidden");
        $("#UserDisplayDiv").css("visibility", "hidden");

        $.ajax({
            type: "POST",
            url: "/UserSearch/GetSearchParamsByUserId",
            data: { "UserId": $('#UserId').val() },
            success: function (response) {
                $("#ParamSearchDiv").css("visibility", "visible");
                if (response) {
                    UserSearchParam = JSON.parse(response);
                    SearchParamCount = UserSearchParam.length;
                    if (SearchParamCount == 0) {
                        ShowEmptySearchParamRow();
                    }
                    else {
                        document.getElementById("btnSearch").disabled = false;
                        BuildSearchParamInputControls();
                    }
                }
                else {
                    SearchParamCount = 0;
                    ShowEmptySearchParamRow();
                }
            },
            failure: function (response) { toastr.error(response.responseText) },
            error: function (response) { toastr.error(response.responseText) },
        });

    });

    $('#btnSearch').click(function () {

        var flgValid = true;

        var userid = null;
        var username = null;
        var role = null;
        var lastlogin = null;
        var fname = null;
        var lname = null;
        var department = null;
        var doj = null;
        var mgrid = null;
        var seniority = null;
        var empcode = null;

        $(UserSearchParam).each(function (index) {

            var fieldname = UserSearchParam[index].FieldName;
            var control = document.getElementById('' + fieldname + '');

            var controlValue = '';

            if ($(control).prop('type') == 'select-one') {
                controlValue = $(control).children("option").filter(":selected").text();
            }
            else {
                controlValue = control.value;
            }

            if (control.value) {
                if (fieldname == 'UserId') userid = controlValue;
                if (fieldname == 'UserName') username = controlValue;
                if (fieldname == 'Role') role = controlValue;
                if (fieldname == 'LastLogin') lastlogin = controlValue;
                if (fieldname == 'FName') fname = controlValue;
                if (fieldname == 'LName') lname = control.value;
                if (fieldname == 'Department') department = controlValue;
                if (fieldname == 'DOJ') doj = controlValue;
                if (fieldname == 'MgrId') mgrid = controlValue;
                if (fieldname == 'Seniority') seniority = controlValue;
                if (fieldname == 'EmpCode') empcode = controlValue;
            }

            if (UserSearchParam[index].Constraint == 'Mandatory') {
                if (!control.value) {
                    $(control).addClass("error");
                    return flgValid = false;
                }
                else {
                    $(control).removeClass("error");
                }
            }
            else {
                $(control).removeClass("error");
            }

        });

        if (flgValid) {
            $.ajax({
                type: "POST",
                url: "/UserSearch/SearchUserBySearchParams",
                data: {
                    "userid": userid, "username": username, "role": role, "lastlogin": lastlogin, "fname": fname, "lname": lname,
                    "department": department, "doj": doj, "mgrid": mgrid, "seniority": seniority, "empcode": empcode
                },
                success: function (response) {

                    $("#UserDisplayDiv").css("visibility", "visible");
                    if (response) {
                        UserSearchResult = JSON.parse(response);
                        UserSearchResultCount = UserSearchResult.length;
                        if (UserSearchResultCount == 0) {
                            ShowEmptySearchResultRow();
                        }
                        else {
                            BuildUserSearchResultTable();
                        }
                    }
                    else {
                        UserSearchResultCount = UserSearchResult.length;
                        ShowEmptySearchResultRow();
                    }

                },
                failure: function (response) { toastr.error(response.responseText) },
                error: function (response) { toastr.error(response.responseText) },
            });
        }

    });

    

</script>